services:
  - type: web
    name: telegram-scheduler-bot
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: BOT_TOKEN
        sync: false  # ستضيفه يدوياً في لوحة التحكم
      - key: ADMIN_ID
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: TZ
        value: Asia/Riyadh
    healthCheckPath: /
    autoDeploy: true
